OnlineEdu.WebUI/Areas/Admin/Controllers/BlogCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using NuGet.DependencyResolver;
using OnlineEdu.WebUI.DTOs.AboutDtos;
using OnlineEdu.WebUI.DTOs.BlogCategoryDtos;
using OnlineEdu.WebUI.Helpers;
using OnlineEdu.WebUI.Validators;

namespace OnlineEdu.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("[area]/[controller]/[action]/{id?}")]
    public class BlogCategoryController : Controller
    {
        private readonly HttpClient _client = HttpClientInstance.CreateClient();
        public async Task<IActionResult> Index()
        {

            var values = await _client.GetFromJsonAsync<List<ResultBlogCategoryDto>>("blogcategories");
            return View(values);
        }

        public async Task<IActionResult> DeleteBlogCategory(int id)
        {
            await _client.DeleteAsync($"blogcategories/{id}");
            return RedirectToAction(nameof(Index));
        }


        public IActionResult CreateBlogCategory()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> CreateBlogCategory(CreateBlogCategoryDto createBlogCategoryDto)
        {
            var validator = new BlogCategoryValidator();
           var result =  await validator.ValidateAsync(createBlogCategoryDto);
            if (!result.IsValid)
            {
                ModelState.Clear();
                foreach (var x in result.Errors)
                {
                    ModelState.AddModelError(x.PropertyName, x.ErrorMessage);
                }
                return View();
            }
            await _client.PostAsJsonAsync("blogcategories", createBlogCategoryDto);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UpdateBlogCategory(int id)
        {
            var values = await _client.GetFromJsonAsync<UpdateBlogCategoryDto>($"blogcategories/{id}");
            return View(values);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateBlogCategory(UpdateBlogCategoryDto updateBlogCategoryDto)
        {
            await _client.PutAsJsonAsync("blogcategories", updateBlogCategoryDto);
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineEdu.WebUI/Areas/Admin/Views/BlogCategory/CreateBlogCategory.cshtml
@model CreateBlogCategoryDto
@{
    ViewData["Title"] = "Yeni Blog Kategorisi Ekleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<form method="post">
   
    <label>Blog Kategorisi Adı</label>
    <input type="text" asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
    <br />
    
    <button class="btn btn-outline-primary">Kaydet</button>
</form>

OnlineEdu.WebUI/Areas/Admin/Views/BlogCategory/Index.cshtml
@model List<ResultBlogCategoryDto>
@{
    ViewData["Title"] = "Blog Kategorileri";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



@{
    int count = 0;
}
<table class="table table-hover">
    <tr>
        <th>#</th>
        <th>Blog Kategori Adı</th>

        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        count++;
        <tr>
            <th>@count</th>
            <td>@item.Name</td>
            <td>
                <button onclick="deleteBlogCategory(@item.BlogCategoryId)" class="btn btn-outline-danger">Sil</button>
                <a asp-action="UpdateBlogCategory" asp-controller="BlogCategory" asp-area="Admin" asp-route-id="@item.BlogCategoryId" class="btn btn-outline-info">Güncelle</a>


            </td>
        </tr>
    }
</table>

<br />
<a asp-action="CreateBlogCategory" asp-controller="BlogCategory" asp-area="Admin" class="btn btn-outline-primary">Yeni Blog Kategorisi Ekle</a>

<script>

    function deleteBlogCategory(id) {



                Swal.fire({
  title: "Silmek istediğinize emin misiniz?",
  text: "Bu işlemi geri alamazsınız!",
  icon: "warning",
  showCancelButton: true,
  confirmButtonColor: "#3085d6",
  cancelButtonColor: "#d33",
  confirmButtonText: "Evet, Sil!",
  cancelButtonText: "İptal"
}).then((result) => {
  if (result.isConfirmed) {
   
      window.location.href = "/Admin/BlogCategory/DeleteBlogCategory/" + id;

  }
});

    }

</script>

OnlineEdu.WebUI/Areas/Admin/Views/BlogCategory/UpdateBlogCategory.cshtml
@model UpdateBlogCategoryDto
@{
    ViewData["Title"] = "Blog Kategorisi Güncelleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<form method="post">
    <input type="hidden" asp-for="BlogCategoryId" />
    <label>Blog Kategorisi Adı</label>
    <input type="text" asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
    <br />

    <button class="btn btn-outline-primary">Güncelle</button>
</form>